-- Auth (issue #18) + reivindicação de clube (issue #19).
-- Compatível com H2 (MODE=PostgreSQL) e PostgreSQL.

CREATE TABLE users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(30)  NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    club_id       BIGINT       NULL
);

CREATE UNIQUE INDEX uq_users_username ON users(username);

-- Lock otimista para o `claim`: o segundo de dois claims simultâneos no mesmo
-- clube perde a checagem de versão e recebe 409.
ALTER TABLE clubs ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
